# Second Workflow (e.g., `.github/workflows/use-artifacts.yml`)
name: 'Helm Chart Setup'

on:
  
  workflow_run:
    workflows: ["Terraform Plan/Apply"]
    types:
      - completed


env:
  ARM_CLIENT_ID: "${{ secrets.ARM_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: AKS get-cred
        working-directory: ./Provision-Infrastructure
        run: |
          yaml_file="./Provision-Infrastructure/modules/DeploymentPrep/prep_deployment.yaml"

          # Extract values using yq
          resource_group_name=$(yq eval '.AzureResources.AKS.ResourceGroup' "$yaml_file")
          aks_name=$(yq eval '.AzureResources.AKS.name' "$yaml_file")

          echo "Resource Group Name for AKS: $resource_group_name"
          echo "AKS Name: $aks_name"
          echo "Resource Group Name for Backend Storage: $backend_storage_rg"

          az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          az aks get-credentials --resource-group $resource_group_name  --name $aks_name

          


      - name: Helm Install/Upgrade Nginx ingress Controller
        working-directory: ./Provision-Infrastructure
        run: |
          helm upgrade --install external \
          --repo https://kubernetes.github.io/ingress-nginx \
          ingress-nginx \
          --namespace ingress \
          --create-namespace \
          --version 4.8.0 \
          --values path/to/values/ingress.yaml


